[project]
name = "btraderoption"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
]
